.Dd May 19, 2014
.Dt STATIC-SERVER \&1 "STATIC-SERVER MANUAL"
.Os STATIC-SERVER VERSION
.Sh NAME
.Nm static-server 
.Nd serves the contents of a given directory tree over http 
.Sh SYNOPSIS
.Nm static-server
.Oo
.Em OPTIONS Ns 
.Oc
.Sh DESCRIPTION
The 
.Sy static-server
utility servers the contents of a given directory tree over http.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl r Ns , Fl -root Ns = Ns Aq Ar directory
Root directory to server from.
Default: "."
.It Fl -listen Ns = Ns Aq Ar address:port
Address and port to listen to, as a string of "address:port".
Default: "0.0.0.0:8080"
.It Fl -ssl-listen Ns = Ns Aq Ar address:port
Address and port to listen via SSL to, as a string of "address:port".
.It Fl -ssl-key Ns = Ns Aq Ar ssl-key-file
Path to ssl private key. Default: key.pem
.It Fl -ssl-cert Ns = Ns Aq Ar ssl-cert-file
Path to ssl certificate. Default: cert.pem
.It Fl v Ns , Fl -verbose
Show verbose (debug) level log output
.It Fl V Ns , Fl -version
Print version and exit; specify twice to show license information
.It Fl h Ns , Fl -help
Show help output and exit
.El
.Sh EXAMPLES
Serve from /tmp/images:
.Bd -literal
 static-server -d /tmp/images
.Ed
.Pp
Serve from CWD, and listen on an alternate port:
.Bd -literal
 static-server -l 0.0.0.0:9999
.Ed
.Sh WWW
https://github.com/cactus/static-server
