// Copyright (c) 2012-2016 Eli Janssen
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

package main

const licenseText = `
This software is available under the MIT License at:
└── https://github.com/cactus/static-server

Portions of this software utilize third party libraries:
├── Go std library
│   └── net/http/fs.go imported/modified        (BSD-style)
└── https://github.com/jessevdk/go-flags        (BSD License)
`